version: "3.9"

services:
  mongodb:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_DATABASE: sample
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
